In [1]:
import torch
from d2l import torch as d2l

`corr2d_multi_in` 函数实现了多输入通道的互相关操作

In [11]:
def corr2d_multi_in(X, K):
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K)) # zip 对最外面的维度做遍历

In [9]:
X = torch.arange(27, dtype=torch.float32).reshape((3, 3, 3))
K = torch.ones(12, dtype=torch.float32).reshape((3,2,2))
X, K

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.]],
 
         [[ 9., 10., 11.],
          [12., 13., 14.],
          [15., 16., 17.]],
 
         [[18., 19., 20.],
          [21., 22., 23.],
          [24., 25., 26.]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [10]:
corr2d_multi_in(X, K)

tensor([[132., 144.],
        [168., 180.]])

`corr2d_multi_in_out` 函数实现多输入，多输出通道的互相关操作

In [14]:
def corr2d_multi_in_out(X, K):
    """ 这里的 K 是 4 维的，把每一维的三维核拿出来做多输入互相关再放入 stack 中 """
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0) # 0 代表最外面那一维度（输出通道）做栈堆放

In [16]:
K = torch.ones(36, dtype=torch.float32).reshape((3, 3, 2, 2))
K.shape

torch.Size([3, 3, 2, 2])

In [17]:
corr2d_multi_in_out(X, K)

tensor([[[132., 144.],
         [168., 180.]],

        [[132., 144.],
         [168., 180.]],

        [[132., 144.],
         [168., 180.]]])

`corr2d_multi_in_out_1x1` 函数实现 $1 \times 1$ 卷积

In [20]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    Y = torch.mm(K, X)
    return Y.reshape((c_o, h, w))

In [22]:
K = torch.ones(9, dtype=torch.float32).reshape((3, 3, 1, 1))
Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)
Y1 == Y2

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])