### 池化层运算

实现池化层正向传播

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [35]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    X_h, X_w = X.shape
    Y_h = X_h - p_h + 1
    Y_w = X_w - p_w + 1
    Y = torch.zeros(Y_h, Y_w)
    for i in range(Y_h):
        for j in range(Y_w):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            if mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()

    return Y

In [38]:
X = torch.arange(9.).reshape(3, 3)
pool_size = (2, 2)
Y = pool2d(X, pool_size, mode='avg')
X, Y

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]),
 tensor([[2., 3.],
         [5., 6.]]))

### 填充和步幅

使用 `torch` 框架提供的方法，分别是最大池化和平均池化

In [50]:
X = torch.arange(9.).reshape(1, 1, 3, 3) # 输入批量大小，通道数，高宽
torch_maxPool2d = nn.MaxPool2d(2, stride=1) # pytorch 框架中池化层的步幅默认和池化窗口大小相同（不重叠），但也可以更改
torch_maxPool2d(X)

tensor([[[[4., 5.],
          [7., 8.]]]])

In [53]:
torch_avgPool2d = nn.AvgPool2d(2, stride=1)
torch_avgPool2d(X)

tensor([[[[2., 3.],
          [5., 6.]]]])