## 线性代数
标量由只有一个元素的张量表示

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y ## x**y 是指数运算

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
x = torch.arange(4)

访问张量长度

In [3]:
len(x)

4

通过指定分量 $m$ , $n$ 来创建一个形状为 $m * n$ 的矩阵

In [4]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [5]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

`clone()`可以重新分配内存，将 A 的一个副本分配给 B，而简单的`B = A`只是更改了 A 的索引

In [6]:
B = A.clone()
B

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

两个矩阵按元素乘法称为*哈达玛积（Hadamard product）*

In [7]:
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

当一个标量与一个矩阵做算术运算，意味着这个矩阵所有元素都会与这个标量做算术运算

In [8]:
a = 2
X = torch.arange(20).reshape(5, 4)
X, a + X, a * X

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13],
         [14, 15, 16, 17],
         [18, 19, 20, 21]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]))

指定维度求和张量，其中参数`axis`代表维度值，从 0 开始，与`reshape()`中的参数对应

如二维张量的`sum(axis = 0)`代表按行求和，既将所有行加为一行

In [9]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
A.sum(axis = 0)

tensor([40, 45, 50, 55])

多维张量求和也类似，若对第 0 维求和，空间上就是前后相加，可以加以意会

In [11]:
B = torch.arange(20 * 2).reshape(2, 5, 4) #batch = 2
B

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [12]:
B.sum(axis = 0), B.sum(axis = 1), B.sum(axis = 2)

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 tensor([[  6,  22,  38,  54,  70],
         [ 86, 102, 118, 134, 150]]))

也可以同时对多个维度求和，对哪个维度求和，形状就成为剩下形状的样子

In [13]:
B, B.sum(axis = 0), B.sum(axis = [0, 1]) #先对 0 维相加，再对 1 维求和

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 tensor([180, 190, 200, 210]))

与求和相关的操作是求均值

In [14]:
A = torch.arange(20, dtype = torch.float32).reshape(5, 4)
A.mean(), A.sum() / A.numel() #操作等价

(tensor(9.5000), tensor(9.5000))

均值也可以和求和一样按维度求

In [15]:
A, A.mean(axis = 0), A.sum(axis = 0) / A.shape[0] # 操作等价，shape[0]的意思是行数（0维形状）

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]))

In [16]:
A.sum(axis = 1)

tensor([ 6., 22., 38., 54., 70.])

使用`keepdims = True`参数使得计算总和后轴数保持不变

In [28]:
A, A.sum(axis = 1, keepdims = True)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[10.],
         [35.],
         [60.],
         [85.]]))

计算矩阵某个轴的累计总和，例如当`axis = 0`时，按行从上到下加下来（第一行加到第二行...），既行变换

In [18]:
A.cumsum(axis = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

使用`torch.dot()`求向量点积

In [19]:
a = torch.ones(5, dtype = torch.float32)
b = torch.arange(5, dtype = torch.float32)
a, b

(tensor([1., 1., 1., 1., 1.]), tensor([0., 1., 2., 3., 4.]))

In [20]:
torch.dot(a, b), torch.sum(a * b) #两者操作一致

(tensor(10.), tensor(10.))

使用`torch.mv()--matrix, vector`让矩阵和向量点乘

In [21]:
A = torch.arange(20, dtype = torch.float32).reshape(4, 5)
x = torch.ones(5, dtype = torch.float32)
A, x

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([1., 1., 1., 1., 1.]))

In [22]:
torch.mv(A, x)

tensor([10., 35., 60., 85.])

使用`torch.mm()--matrix, matrix`做矩阵之间的点积

In [23]:
B = torch.arange(20, dtype = torch.float32).reshape(5, 4)

In [24]:
torch.mm(A, B)

tensor([[120., 130., 140., 150.],
        [320., 355., 390., 425.],
        [520., 580., 640., 700.],
        [720., 805., 890., 975.]])

$L_2$ 范数是向量元素平方和的平方根

In [25]:
y = torch.tensor([3.0, -4.0])
torch.norm(y)

tensor(5.)

$L_1$ 范数就是向量元素的绝对值求和

In [26]:
torch.abs(y).sum()

tensor(7.)

矩阵的 *佛罗贝尼乌斯范数（Frobenius norm）* 是矩阵元素平方和的平方根

In [27]:
torch.norm(A)

tensor(49.6991)